version: '3'
x-mlops-common:
  &mlops-common
  image: udacity/mlops_tests_2
  user: root
  mem_limit: 6G
  mem_reservation: 256M
  cpus: 2
  container_name: mlops_tests
  environment:
    &mlops-common-env
    TZ: "America/Sao_Paulo"
  ports:
    - "8080:8080"
    - "8888:8888"
    - "5000:5000"
  volumes:
    - ~/.aws/:/root/.aws
    - ../mlops-on-heroku-fastapi/:/root/project
    - ~/.gitconfig:/root/.gitconfig
    - ./scripts/.vimrc:/root/.vimrc

services:

  mlops:
    <<: *mlops-common
    environment:
      <<: *mlops-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"

  dvc-push-data:
    <<: *mlops-common
    profiles:
      - debug
    environment:
      <<: *mlops-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command: >
      bash -c """
      source activate mlops_exercise
      && cd /root/project
      && dvc add nd0821-c3-starter-code/starter/data/census.csv
      && git add nd0821-c3-starter-code/starter/data/census.csv.dvc nd0821-c3-starter-code/starter/data/.gitignore
      && git commit || echo '...noting to commit ...'
      && dvc push -r s3data
      """