name: mlops_exercise
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - seaborn=0.11.1
  - pandas=1.2.3
  - pytest=6.2.2
  - pip=20.3.3
  - git=2.30.2
  - pyarrow=2.0
  - requests=2.24.0
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - pillow=8.1.2
  - pydantic
  - uvicorn
  - gunicorn
  - pylint
  - autopep8
  - dataclasses
  - pip:
      - fastapi==0.63.0